# Generated by Django 3.0.8 on 2020-07-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
